#187570716 - chore :setup unit teting with jest
atlp-rwanda/e-commerce-furebo-32-bn pull request #2
Opened 2024-05-12 14:11 UTC by jamesndekezi

## What does this PR does?

this PR setup initila unit testing for our backend api

## How can this be tested?

1.Clone repo
2. install dependencies
3. run test by `npm run test`

## Pivot tracker id -> #187570716

##screenshots
![mnbcxx](https://github.com/atlp-rwanda/e-commerce-furebo-32-bn/assets/111005167/7d5848c5-ec37-4552-95fe-39197f110ff3)

2024-05-13 02:33 UTC, mugishaj092 requested changes
Hi James, thanks for the pull request. Just a quick note, the task description specified using Mocha Chai for testing, but I noticed Jest was used instead. Let's ensure consistency with the task requirements. Could you please revise the tests to use Mocha Chai as described? Appreciate your attention to this detail!

2024-05-15 12:11 UTC, SHYAKA-Aime approved these changes

2024-05-15 12:28 UTC, mugishaj092 approved these changes
Great job

2024-05-16 13:20 UTC, SHYAKA-Aime approved these changes

2024-05-20 09:46 UTC, furebo approved these changes

2024-05-20 09:46 UTC, merged