Ft verification email validation
atlp-rwanda/e-commerce-furebo-32-bn pull request #23
Opened 2024-05-24 13:22 UTC by kennyg37

#### What does this PR do?
configures an automatic email as soon as a user signs up and validates the user using a jwt token connected to 
a link in the email
#### Describe your changes
added a controller file to handle the token verification after the link is clicked
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)

#### Screenshots (if is appropriate)

2024-05-27 05:46 UTC, mugishaj092 requested changes
generateVerificationToken function it's not necessary you can reuse generateToken and add tests

2024-05-27 08:53 UTC, GabrielDushime approved these changes

2024-05-27 12:04 UTC, mutsinziisaac submitted a review, later dismissed

2024-05-27 17:03 UTC, GabrielDushime submitted a review, later dismissed
Good

2024-05-28 10:53 UTC, mugishaj092 submitted a review, later dismissed

2024-05-28 11:40 UTC, SHYAKA-Aime approved these changes

2024-05-29 13:45 UTC, didasmbalanya requested changes
Good job so far but there are a few changes I have pointed out. please look into them

2024-05-29 13:45 UTC, didasmbalanya commented on .env.example
> +FRONTEND_URL =
Add empty line at the end of each file

2024-05-29 13:45 UTC, didasmbalanya commented on src/controllers/user.controller.ts
> +    const html = `<p>Please verify your email by clicking on the following link:</p><a href="${verificationLink}">Verify Email</a>`;
Move this to your email sending logic

2024-05-29 13:45 UTC, didasmbalanya commented on src/controllers/verifyUser.controller.ts
> +    }
Move this to a middleware and make it reuseable

2024-05-29 13:45 UTC, didasmbalanya commented on src/controllers/verifyUser.controller.ts
> +    const authToken = await generateToken(user, "24h");
Make the token validity period configurable. i.e an env

2024-05-29 13:45 UTC, didasmbalanya commented on src/controllers/verifyUser.controller.ts
> +    return res.status(500).json({ message: "Invalid token" });
Handle better

2024-05-29 13:45 UTC, didasmbalanya commented on src/utils/tokenGenerator.utils.ts
> +const generateToken = async (user: UserAttributes, expiresIn: string = "30d") => {
Make the expiry cofigurable

2024-06-03 10:48 UTC, closed without merging