Reset Password via email
atlp-rwanda/e-commerce-furebo-32-bn pull request #26
Opened 2024-05-27 13:06 UTC by jamesndekezi

#### What does this PR do?

Reset Password via email

#### Describe your changes

This PR adds the functionality to reset a user's password via email. When a user forgets their password, they can request a reset, and an email with a reset link will be sent to them. This link allows the user to reset their password securely.

#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no API changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other

#### How should this be manually tested?

Go to the login page and click on "Forgot Password".
Enter the registered email address.
Check the email inbox for a reset link.
Click on the reset link and set a new password.
Verify that the new password works for logging into the application.

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)

#### Screenshots (if is appropriate)
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?

Navigate to the login page and click on "Forgot Password".
Enter the registered email address.
Check the email inbox for a reset link.
Click on the reset link and set a new password.
Verify that the new password works for logging into the application.
![ffw](https://github.com/atlp-rwanda/e-commerce-furebo-32-bn/assets/111005167/7e17d376-198e-49d1-b761-a86cefa712e7)
![ffw](https://github.com/atlp-rwanda/e-commerce-furebo-32-bn/assets/111005167/abe6504c-690a-4f8c-89f1-6f4d1a1ad2f4)

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)

#### Screenshots (if is approp
![ffw](https://github.com/atlp-rwanda/e-commerce-furebo-32-bn/assets/111005167/d4004842-e98d-4c6b-b7fb-551e276b3696)
riate)

2024-05-28 12:54 UTC, GabrielDushime submitted a review, later dismissed

2024-05-30 12:42 UTC, mugishaj092 requested changes
Your code is not working

2024-05-31 08:53 UTC, mugishaj092 commented on eslint.config.js
> +const tseslint = require("typescript-eslint");
This eslint.config.json is not necessary

2024-05-31 08:53 UTC, mugishaj092 commented on .eslintrc.json
> -    "root": true,
Why did you delete this file?

you need to restore it because is neccessary

2024-05-31 08:55 UTC, mugishaj092 commented on src/middlewares/isUserFound.tsx
> +import { NextFunction, Request, Response } from "express";
This is not middleware you can put it in utils

2024-05-31 08:56 UTC, mugishaj092 commented on src/utils/email.utils.ts
This changes was not neccessary

2024-06-03 12:44 UTC, closed without merging