Configure PostgreSQL and Sequelize ORM
atlp-rwanda/e-commerce-furebo-32-bn pull request #3
Opened 2024-05-13 09:31 UTC by mutsinziisaac

This pull request adds the necessary configurations to use PostgreSQL as the database engine and Sequelize ORM for managing database operations in our application. The changes include setting up the database connection, defining models, and configuring Sequelize migrations for maintaining the database schema.

Here's a summary of the changes:

Added Sequelize as a dependency in package.json.
Created a sequelizeConfig.ts file to define the Sequelize connection.
Configured the database connection parameters such as username, password, host, and database name in sequelizeConfig.ts.
Updated the User model to use Sequelize DataTypes and the sequelize connection.
Created a migration file to define the schema for the User table.
Please review and merge these changes to enable PostgreSQL as our database engine and Sequelize ORM for managing database operations.

2024-05-13 10:13 UTC, mugishaj092 approved these changes
Great job Mutsinzi

2024-05-13 10:22 UTC, GabrielDushime commented
Good For your job!Keep pushing

2024-05-13 10:26 UTC, GabrielDushime reviewed
Good Job Bruh!

2024-05-13 10:44 UTC, mugishaj092 requested changes
Can you move models folder into  /src directory

2024-05-13 11:07 UTC, GabrielDushime requested changes
Change model to Model

2024-05-13 11:26 UTC, GabrielDushime approved these changes
Good Job Isaac

2024-05-13 11:44 UTC, mugishaj092 approved these changes
great

2024-05-14 06:35 UTC, furebo requested changes

2024-05-14 06:35 UTC, furebo commented on config/config.json
> +    "dialect": "postgres"
Please make this file a javascript file instead of a json file and put database credentials in environment variables.

2024-05-14 06:35 UTC, furebo commented on sequelizeConfig.ts
> +export default sequelize;
Please consider using a .sequelizerc file for sequelize configuration in the root directory

2024-05-14 06:35 UTC, furebo commented on src/models/index.js
> +    return (
The Models, migrations, configuration, and seeders files must be specified in .sequelizerc file and please put them inside the database folder inside the /src folder.

2024-05-14 06:39 UTC, furebo requested changes

2024-05-14 06:39 UTC, furebo commented on src/models/index.js
> +    return (
Also resolve the conflicts and make sure you have one commit.

2024-05-14 16:53 UTC, furebo approved these changes

2024-05-14 16:55 UTC, furebo commented
Next Time please consider squashing your commits to one commit

2024-05-14 16:57 UTC, merged