Add Profile Page Settings
atlp-rwanda/e-commerce-furebo-32-bn pull request #37
Opened 2024-05-31 13:26 UTC by jamesndekezi

#### What does this PR do?

Allow user to have unique Profile 

#### Describe your changes

Profiles will provide a way to maintain generic and user specific data/info.

#### PR Type

  Feature (ft)

What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://xsolve.atlassian.net/browse/PROJECT_KEY)

#### Screenshots (if is appropriate)

2024-06-04 04:23 UTC, mugishaj092 requested changes
Good job but check my comment

2024-06-04 04:23 UTC, mugishaj092 commented on src/controllers/profile.controller.ts
> +export const getProfileController = async (req: Request, res: Response) => {
i think none to add Controller just getProfile is enough

2024-06-04 04:23 UTC, mugishaj092 commented on src/controllers/profile.controller.ts
> +    const profile = await UserService.getProfileServices(userId);
getProfileService works the same with getYseByid you can check and reuse it instead of writing new one

2024-06-04 04:23 UTC, mugishaj092 commented on src/controllers/profile.controller.ts
> +export const updateProfileController = async (req: Request, res: Response) => {
also you can remove controller just use updateProfileController

2024-06-04 04:23 UTC, mugishaj092 commented on tsconfig.json
> +    // "noUnusedLocals": true,                           /* Enable error reporting when local variables aren't read. */
no need to disable this

2024-06-04 04:23 UTC, mugishaj092 commented on src/database/models/Profile.ts
> +
Because you are working on the profile user so you will use User model i think this profile model is not neccessary

2024-06-06 12:58 UTC, GabrielDushime requested changes
Your test is not running at circleci make sure you corrected that

2024-06-11 15:35 UTC, closed without merging