feat: Add product functionality - includes tests, controllers, routes…
atlp-rwanda/e-commerce-furebo-32-bn pull request #38
Opened 2024-06-03 10:08 UTC by Mugisha146

…, models, services, types, and validations

#### What does this PR do?

Seller can create product,retrieve all product and update product( stock,availability,expireDate ).

#### Describe your changes

Added product model (attribute: id,name,description,price,stock,available,expireDate), product validation, functionality and tests for the endpoint as well as the Swagger Documentation

#### PR Type
What kind of change does this PR introduce?
```
[ ] Feature
[ ] Tests
```

#### How should this be manually tested?

Navigate to the branch and Test the functionality either in Swagger UI or Postman

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570741)

2024-06-03 19:14 UTC, SHYAKA-Aime requested changes
Just Try to improve your test coverage

2024-06-03 19:18 UTC, mutsinziisaac requested changes
work on the test coverage

2024-06-04 03:54 UTC, mugishaj092 commented on __test__/product.test.ts
> +    const sellerUser = {
Create those variable in file called variable.utils.ts and then use it here

2024-06-04 04:07 UTC, mugishaj092 requested changes
Good job so far but i give few feedbacks check comments

2024-06-04 04:07 UTC, mugishaj092 commented on src/database/migrations/20240512215421-create-users.js
> +      name: {
create new product migration file

2024-06-04 04:07 UTC, mugishaj092 commented on src/database/models/product.model.ts
> +  declare id: string;
You forget to add field of picture

2024-06-04 07:28 UTC, closed without merging