[#187570742] As a seller, I can delete a product
atlp-rwanda/e-commerce-furebo-32-bn pull request #55
Opened 2024-06-12 00:12 UTC by vegetason

#### What does this PR do?

A seller should be able to delete a product in his/her collection

#### Describe your changes

I created route for seller to delete a product from a collection

#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[*] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Tests
[ ] Other
```

#### How should this be manually tested?

It can be tested using swagger documentation and postman

#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/n/projects/2703465/stories/187570742)

#### Screenshots (if is appropriate)

2024-06-12 07:32 UTC, mugishaj092 requested changes
Good to go but Solve conflict first

2024-06-12 08:50 UTC, SHYAKA-Aime submitted a review, later dismissed
As you solved conflicts, the functionality also looks good 👏

2024-06-12 08:52 UTC, GabrielDushime submitted a review, later dismissed
Kudos great work now a seller can delete his/her product

2024-06-12 09:32 UTC, jamesndekezi submitted a review, later dismissed
hello after solved conflicts All checks have passed, well done

2024-06-12 10:20 UTC, mugishaj092 requested changes
Good job Try to solve circleCI issue

2024-06-14 06:34 UTC, mugishaj092 requested changes
CircleCi is not is failing

2024-06-14 13:00 UTC, GabrielDushime submitted a review, later dismissed
Great work so that this feature is allowing seller to delete a product

2024-06-14 13:48 UTC, mutsinziisaac submitted a review, later dismissed

2024-06-17 06:29 UTC, jamesndekezi requested changes
Good job, but there some conflicts need to be resolved.
Check on that.

2024-06-17 13:18 UTC, mutsinziisaac submitted a review, later dismissed
looks good

2024-06-17 13:23 UTC, SHYAKA-Aime submitted a review, later dismissed
Good job, Now it is working Well

2024-06-18 05:43 UTC, jamesndekezi submitted a review, later dismissed
Well done, this PR looks fine

2024-06-18 06:39 UTC, GabrielDushime submitted a review, later dismissed

2024-06-18 06:53 UTC, didasmbalanya requested changes

2024-06-18 06:53 UTC, didasmbalanya commented on src/controllers/product.controller.ts
> +  }
This is reusable code that can be done with a middleware

2024-06-18 06:53 UTC, didasmbalanya commented on src/controllers/product.controller.ts
> +  }
This is reusable code that can be done with a middleware

2024-06-18 06:53 UTC, didasmbalanya commented on src/controllers/product.controller.ts
> +  return res.status(200).json({
Use the right status code for a DELETE

2024-06-18 06:53 UTC, didasmbalanya commented on src/routes/product.route.ts
> +router.delete('/deleteProduct/:product_id',protectRoute,restrictTo(userRole.seller),deleteProduct)
The middleware can also check that its not just a seller role but the right seller

2024-06-19 08:57 UTC, GabrielDushime approved these changes
I can see you worked on the requested changes.
No Seller can delete a product from the collection

2024-06-19 09:56 UTC, mutsinziisaac approved these changes

2024-06-19 10:52 UTC, SHYAKA-Aime approved these changes
Looks good and  working well

2024-06-19 11:13 UTC, merged

2024-06-19 11:22 UTC, jamesndekezi reviewed
Well done everything seems to work well