Buyer should be able to checkout
atlp-rwanda/e-commerce-furebo-32-bn pull request #71
Opened 2024-06-14 18:51 UTC by Mugisha146

#### What does this PR do?
Buyer should be able to checkout
#### Describe your changes
This PR introduces an order checkout functionality, including an OrderController with a checkout method, an Order model, related services, and a database migration script and it sets up Express routing for order endpoints and includes unit tests to ensure proper behavior.
#### PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ *] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ *] Tests
[ ] Other
```

#### How should this be manually tested?
using Swagger and Postman
#### What are the relevant pivotal tracker stories?
[Pivotal Tracker Link](https://www.pivotaltracker.com/story/show/187570755)

#### Screenshots (if is appropriate)

2024-06-15 20:27 UTC, SHYAKA-Aime requested changes
On the controller, I think order must come from the products in the Cat, not a form or request body. Also on routes, use protectroute and Restictto(buyer) to ensure only a buyer who is validated can make an order.

2024-06-21 07:49 UTC, mugishaj092 approved these changes

2024-06-21 08:39 UTC, SHYAKA-Aime approved these changes

2024-06-21 08:39 UTC, mutsinziisaac approved these changes

2024-06-21 08:40 UTC, kennyg37 approved these changes

2024-06-21 08:57 UTC, vegetason approved these changes
Well done

2024-06-21 10:17 UTC, merged